# The main config file for your Jekyll template

# Site settings
title: Jackal               # used for the html title of every page
desc: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: https://alecglassford.github.io     # put your website hosting url here
baseurl: '/hia'                 # the subpath of your site, e.g. /blog
permalink: /:categories/:year/:title/   # how should we display posts url

# Meta settings
author: Alec Glassford

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'


# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Blog
    url: /blog/
    desc: The blog of Victoria Badger
  - title: News
    url: /news/
    desc: Stuffs I like to do
  - title: Wiki
    url: /wiki/
    desc: Stuffs I hate to do

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
